name: CD Example Production

on:
  push:
    branches:  
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checkout ke repository code yang kita gunakan

      - name: SSH connect
        uses: appleboy/ssh-action@v1 # Menggunakan action SSH untuk menghubungkan ke server remote
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: | # Script yang akan dijalankan di server remote
            echo "Berhasil terhubung ke server"
            if [ ! -d "/home/FWM/CD-Prod" ]; then
              echo "Folder CD-Prod tidak ditemukan, membuat folder baru"
              mkdir -p /home/FWM/CD-Prod
            else
              echo "Folder CD-Prod sudah ada"
              cd /home/FWM/CD-Prod
              sudo chown -R big-task:big-task CD-Prod
            fi
            echo "Berhasil masuk ke folder CD-Prod"
            
            if [ -d ".git" ]; then
              echo "📁 Repo exists, pulling latest changes..."
              # Update remote dengan token agar pull tidak butuh login
              git remote set-url origin https://${{ secrets.USERNAME }}:${{ secrets.GIT_PAT }}@github.com/${{ secrets.USERNAME }}/CICD-Database.git
              git pull origin main
            else
              echo "📥 Cloning repo for the first time "
              git clone https://${{ secrets.USERNAME }}:${{ secrets.GIT_PAT }}@github.com/${{ secrets.USERNAME }}/CICD-Database.git .
            fi

            echo "✅ Deployment finished at $(date)"
